### ISSUE TITLE
Dogbone and overcut feature

### ISSUE THREAD

**Issue by CptanPanic** [dcowden/featurescript#23]
I found this useful featurescript:

https://forum.onshape.com/discussion/4150/dogbone-and-corner-overcut-features-for-cnc-router-design

**Comment by dcowden** [comment]
@CptanPanic I've notified the author of the possible addition. Without objection from him, I'll ad this:

https://cad.onshape.com/documents/51695bc13e3d9fb286023c70/w/f1e387898ad3a323b9fd9a6b/e/3a9512753b299d5fefc39f46

**Comment by morganb21** [comment]
@CptanPanic @dcowden 
I have got my own featurescript called sheet metal overcut, and it also does normal ones as well.
It is in the list. It has a much easier way to select items. https://cad.onshape.com/documents/b99915c0b73924ca981bc57f/

**Comment by dcowden** [comment]
@morganb21 is yours in the list? if it is already, i'll close this issue. if it is not, lets add yours as well. I'd like to add all known features, even if they overlap/duplicate,  in preparation for later voting/ranking

**Comment by morganb21** [comment]
@dcowden 
Mine is in the list.
It is at the bottom, under sheet metal, called "Sheet Metal Overcut"
