### ISSUE TITLE
Feature Suggestion: Sheet Metal Shaped Flange

### ISSUE THREAD

**Issue by AlnisS** [dcowden/featurescript#36]
I hope I'm submitting this correctly!
This feature allows creating flanges in the shape of a sketch profile. I didn't create it.
Document: https://cad.onshape.com/documents/602655eff016f183fc184978
Forum comment: https://forum.onshape.com/discussion/comment/45245/#Comment_45245

**Comment by mbartlett21** [comment]
Done!
I forgot to add it here :)
