### ISSUE TITLE
Radial Pattern

### ISSUE THREAD

**Issue by morganb21** [dcowden/featurescript#4]
Hello,

The "Radial Pattern" link is broken.
It says "Failed to load document for workspace. Resource does not exist, or you do not have permission to access it."

**Comment by dcowden** [comment]
@morganb21 thanks for reporting this. I pulled that link from here:
https://forum.onshape.com/discussion/comment/20513#Comment_20513

But its dead as you mentioned so i'll remove it.

**Comment by morganb21** [comment]
@dcowden 
Thanks
